In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [28]:
df = pd.read_excel('ins_2018_2020_part2_Batching.xlsx')
df.head()

,MRN,CreatedDate,Batch,Batch2,SiteGroup,Intent1,Category_x,SimApptDuration,TltDose,TxFracs,...,Intent_x,ContrM,Plan75p,Plan80p,Plan90p,Intent_y,PlanM,preTxDays_75,preTxDays_80,preTxDays_90
0,7287,2019-02-20,NaN,NaN,GENITOURINARY(GU),Palliative,Urgent 2,30,1600,2,...,Palliative,0.0,0.0,0.0,1.0,Palliative,0.0,0.0,0.0,1.0
1,7287,2019-07-31,NaN,NaN,GENITOURINARY(GU),Palliative,Urgent 2,30,2500,10,...,Palliative,0.0,0.0,0.0,1.0,Palliative,0.0,0.0,0.0,1.0
2,7287,2019-08-28,NaN,NaN,GENITOURINARY(GU),Palliative,Urgent 2,30,1600,2,...,Palliative,0.0,0.0,0.0,1.0,Palliative,0.0,0.0,0.0,1.0
3,160063,2019-12-02,1.0,1.0,GENITOURINARY(GU),Palliative,Urgent 2,30,2000,5,...,Palliative,0.0,0.0,0.0,1.0,Palliative,0.0,0.0,0.0,1.0
4,160063,2020-07-13,NaN,NaN,GENITOURINARY(GU),Palliative,Urgent 2,30,800,1,...,Palliative,0.0,0.0,0.0,1.0,Palliative,0.0,0.0,0.0,1.0

In [29]:
df=df[df['Batch'].notnull()]
df.shape

(1042, 34)

In [4]:
all_dates = df['CreatedDate'].unique()
len(all_dates)

67

In [6]:
all_dates[66] # total 0 - 66 indexes

numpy.datetime64('2020-02-28T00:00:00.000000000')

Empty DataFrame
Columns: [MRN, CreatedDate, Batch, Batch2, SiteGroup, Intent1, Category_x, SimApptDuration, TltDose, TxFracs, TxApptDuration, TxUnit, Team, CT, linacs, TxStartDt, WaitTime, WaitTime(weekday), priority, targetWait, CreatedDay, Contr75p, Contr80p, Contr90p, Intent_x, ContrM, Plan75p, Plan80p, Plan90p, Intent_y, PlanM, preTxDays_75, preTxDays_80, preTxDays_90]
Index: []

[0 rows x 34 columns]

In [54]:
# created Batch 2 number based on the batching interval
df_batch = pd.DataFrame(columns=df.columns)
batch = 1
i=0
while i <= 63: # batch number until 65 (= 63, 64, 65)
    df_target = df[(df['CreatedDate']==all_dates[i])|
                   (df['CreatedDate']==all_dates[i+1])|
                   (df['CreatedDate']==all_dates[i+2])]
    df_target['Batch2'] = batch
    df_batch = df_batch.append(df_target, ignore_index=True)
    i += 3
    batch += 1
    
# add batch 66
df_target = df[(df['CreatedDate']==all_dates[i])]
df_target['Batch2'] = batch
df_batch = df_batch.append(df_target, ignore_index=True)

/Users/fanjia/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [55]:
df_batch

,MRN,CreatedDate,Batch,Batch2,SiteGroup,Intent1,Category_x,SimApptDuration,TltDose,TxFracs,...,Intent_x,ContrM,Plan75p,Plan80p,Plan90p,Intent_y,PlanM,preTxDays_75,preTxDays_80,preTxDays_90
0,160063,2019-12-02,1.0,1,GENITOURINARY(GU),Palliative,Urgent 2,30,2000,5,...,Palliative,0.0,0.0,0.0,1.0,Palliative,0.0,0.0,0.0,1.0
1,1303927,2019-12-02,1.0,1,BREAST,Radical,Standard 3,30,5000,25,...,Radical,1.0,1.0,1.0,3.0,Radical,0.0,2.0,3.0,5.0
2,4654854,2019-12-02,1.0,1,BREAST,Radical,Standard 3,30,5000,25,...,Radical,1.0,1.0,1.0,3.0,Radical,0.0,2.0,3.0,5.0
3,907979,2019-12-02,1.0,1,BREAST,Palliative,Urgent 2,30,2000,5,...,Palliative,0.0,1.0,1.0,4.0,Palliative,1.0,1.0,1.0,4.0
4,4653015,2019-12-02,1.0,1,SARCOMA,Radical,Standard 3,45,5040,28,...,Radical,1.0,2.0,3.0,5.0,Radical,1.0,5.0,6.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,868506,2020-02-28,14.0,23,LUNG,Palliative,Standard 3,30,2000,5,...,Palliative,1.0,1.0,1.0,4.0,Palliative,0.0,2.0,2.0,5.0
1038,4695636,2020-02-28,14.0,23,CNS,Radical,Standard 3,30,6000,30,...,Radical,1.0,0.0,1.0,2.0,Radical,0.0,1.0,3.0,4.0
1039,4653862,2020-02-28,14.0,23,CNS,Palliative,Standard 3,30,2000,5,...,Palliative,0.0,1.0,1.0,3.0,Palliative,0.0,1.0,1.0,4.0
1040,4281599,2020-02-28,14.0,23,CNS,Palliative,Urgent 2,45,2000,5,...,Palliative,0.0,1.0,1.0,3.0,Palliative,0.0,1.0,1.0,3.0
1041,4689729,2020-02-28,14.0,23,LYMPHOMA,Radical,Standard 3,45,1200,6,...,Radical,1.0,1.0,1.0,4.0,Radical,1.0,3.0,4.0,8.0

In [56]:
target_batch = 'Batch2'
#df_batch = df[df[target_batch].notnull()]
df_batch.head()

,MRN,CreatedDate,Batch,Batch2,SiteGroup,Intent1,Category_x,SimApptDuration,TltDose,TxFracs,...,Intent_x,ContrM,Plan75p,Plan80p,Plan90p,Intent_y,PlanM,preTxDays_75,preTxDays_80,preTxDays_90
0,160063,2019-12-02,1.0,1,GENITOURINARY(GU),Palliative,Urgent 2,30,2000,5,...,Palliative,0.0,0.0,0.0,1.0,Palliative,0.0,0.0,0.0,1.0
1,1303927,2019-12-02,1.0,1,BREAST,Radical,Standard 3,30,5000,25,...,Radical,1.0,1.0,1.0,3.0,Radical,0.0,2.0,3.0,5.0
2,4654854,2019-12-02,1.0,1,BREAST,Radical,Standard 3,30,5000,25,...,Radical,1.0,1.0,1.0,3.0,Radical,0.0,2.0,3.0,5.0
3,907979,2019-12-02,1.0,1,BREAST,Palliative,Urgent 2,30,2000,5,...,Palliative,0.0,1.0,1.0,4.0,Palliative,1.0,1.0,1.0,4.0
4,4653015,2019-12-02,1.0,1,SARCOMA,Radical,Standard 3,45,5040,28,...,Radical,1.0,2.0,3.0,5.0,Radical,1.0,5.0,6.0,9.0

In [57]:
batches = df_batch[target_batch].unique()
for b in batches:
    df_focus = df_batch[df_batch[target_batch] == b]
    dates = df_focus['CreatedDate'].unique()
    createdDay = 0
    for i in dates:
        df_batch.loc[(df_batch['CreatedDate']==i)&(df_batch[target_batch]==b), 'CreatedDay'] = createdDay
        #df.loc[df[<some_column_name>] == <condition>, [<another_column_name>]]
        createdDay += 1

In [58]:
df_batch[df_batch[target_batch]==2][['MRN','CreatedDate','Batch2','CreatedDay']]

        MRN CreatedDate Batch2 CreatedDay
52  3179861  2019-12-05      2          0
53  6226703  2019-12-05      2          0
54   993371  2019-12-05      2          0
55  4365835  2019-12-05      2          0
56  4525359  2019-12-05      2          0
57   698290  2019-12-05      2          0
58  3980611  2019-12-05      2          0
59  4293628  2019-12-05      2          0
60  4475135  2019-12-05      2          0
61  4690640  2019-12-05      2          0
62  4694724  2019-12-05      2          0
63  4698932  2019-12-05      2          0
64  2461225  2019-12-05      2          0
65  4700246  2019-12-05      2          0
66  4347908  2019-12-05      2          0
67  2994234  2019-12-05      2          0
68  4697419  2019-12-05      2          0
69   778648  2019-12-06      2          1
70  2259706  2019-12-06      2          1
71  3683883  2019-12-06      2          1
72  4643680  2019-12-06      2          1
73  4681346  2019-12-06      2          1
74  4691031  2019-12-06      2          1
75  1021016  2019-12-06      2          1
76  4079392  2019-12-06      2          1
77  4698956  2019-12-06      2          1
78  3954114  2019-12-06      2          1
79   789869  2019-12-06      2          1
80  3860845  2019-12-06      2          1
81  3712695  2019-12-06      2          1
82   502519  2019-12-06      2          1
83  4173965  2019-12-06      2          1
84   589093  2019-12-09      2          2
85   644188  2019-12-09      2          2
86   801719  2019-12-09      2          2
87  6290450  2019-12-09      2          2
88  4674930  2019-12-09      2          2
89  2262615  2019-12-09      2          2
90  4205015  2019-12-09      2          2
91  2213398  2019-12-09      2          2
92  3264734  2019-12-09      2          2
93  4688897  2019-12-09      2          2
94  2979167  2019-12-09      2          2
95  2219683  2019-12-09      2          2
96  2725585  2019-12-09      2          2

In [60]:
df_batch.to_excel('ins_2020_part3_batching_3d.xlsx')